#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export DOTFILES="$HOME/Environment/dotfiles"
export LOCALBIN="$HOME/bin:$DOTFILES/bin"

export PATH="$LOCALBIN:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Sometimes needed for installing things
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

alias wow='git status'
alias such='git'
alias very='git'
alias text-changes='git diff --color-words'

alias edit_env='vim ~/Environment/dotfiles'
alias du='du -h'

NVIM_HOME='~/Documents/Notes'
alias nvim='~/.janus/nvim/nvim'

export PYTHONDONTWRITEBYTECODE=True
export PIP_RESPECT_VIRTUALENV=true

function killport () {
  kill -9 `lsof -t -i :$1`
}

precmd() { print "" }

if [[ $(uname) == 'Linux' ]]; then

fi

if [[ $(uname) == 'Darwin' ]]; then

fi

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
