#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

. $(brew --prefix)/etc/profile.d/z.sh
# Customize to your needs...
COREUTILS=$(brew --prefix coreutils)/libexec/gnubin

export DOTFILES="$HOME/Environment/dotfiles"
export LOCALBIN="$DOTFILES/bin"

export PATH="$LOCALBIN:/usr/local/bin:$COREUTILS:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto";

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

alias wow='git status'
alias such='git'
alias very='git'
alias text-changes='git diff --color-words'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# PostgreSQL
export PGDATA=$HOME/Library/Databases/PostgreSQL/

# Python Virtualenv

export WORKON_HOME="$HOME/Environment/virtualenvs"
export PROJECT_HOME="$HOME/Development"
source /usr/local/bin/virtualenvwrapper.sh

alias v='workon'
alias v.deactivate='deactivate'
alias v.mk='mkvirtualenv'
alias v.rm='rmvirtualenv'
alias v.switch='workon'
alias v.add2virtualenv='add2virtualenv'
alias v.cdsitepackages='cdsitepackages'
alias v.cd='cdvirtualenv'
alias v.lssitepackages='lssitepackages'

alias edit_env='mvim ~/Environment/dotfiles'

export PYTHONDONTWRITEBYTECODE=True
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

function killport () {
  kill -9 `lsof -t -i :$1`
}
